### ISSUE TITLE
npm-stats website  is down

### ISSUE THREAD

**Issue by sterpe** [matteofigus/npm-stats-www#15]
All packages have no data.  E.g. http://www.npm-stats.com/sterpe

**Comment by matteofigus** [comment]
It looks like npm api stopped serving data for packages more than 1 year old.
https://api.npmjs.org/downloads/range/2016-01-01:2017-04-10/oc
This for instance returns an error
```js
{
error: "exceeded max days of 365"
}
```

**Comment by sterpe** [comment]
Whoa, that is weird @isaacs  -- why no stats data for packages older than 1 year?

**Comment by matteofigus** [comment]
Opened an issue here https://github.com/npm/download-counts/issues/31 - I suspect there may be some other underlining issue, as I see no recent code changes and I'm quite sure this used to work smoothly a couple of days ago!

**Comment by sterpe** [comment]
Subscribed to that issue as well, thanks.

**Comment by matteofigus** [comment]
So it looks like that is caused by a breaking change of the api - we don't have a unique endpoint for getting all the downloads of a given module, but need to make multiple calls to get 365 days data and then aggregate in another step. 

May be something I can try to tackle during the week-end. Apologies for the inconvenience.

**Comment by OmgImAlexis** [comment]
Maybe get in contact with the people running npm-stat.com they seem to have it working fine.

Ref: https://npm-stat.com/charts.html?package=cz&from=2016-04-13&to=2017-04-13

**Comment by matteofigus** [comment]
no, the problem is for an interval for more than 365 days. I can reproduce the same issue if I go here:
https://npm-stat.com/charts.html?package=cz&from=2016-04-12&to=2017-04-13

**Comment by OmgImAlexis** [comment]
Yes but your site doesn't show anything at all, they at least work with 365 days.

**Comment by matteofigus** [comment]
It just restarted working. I was actually planning to work on that but I guess npm api change was reverted. Shame there is little transparency on this api changes :(
