### ISSUE TITLE
Shut down or just temporary broken?

### ISSUE THREAD

**Issue by tunnckoCore** [matteofigus/npm-stats-www#20]
Shows: `An error occurred while trying to retrieve the results`

**Comment by doowb** [comment]
NPM's `skimdb` server is down https://npm.community/t/skimdb-is-down-for-me-anyone-else/8060
This is where this site gets the list of packages a maintainer has and some other data about packages.

**Comment by tunnckoCore** [comment]
So swapping https://github.com/hughsk/npm-stats/blob/master/index.js#L14 with the new registry, will work?

**Comment by matteofigus** [comment]
Hi friends, unfortunately I don't have a lot of time to fix this. I am going to fix it eventually, but if anyone would like to pick this up earlier with a pull request, I would be happy to help with reviews and deployment

**Comment by matteofigus** [comment]
As far as I understand, the data source used by `npm-stats` is not working and that library is not actively maintained anymore. Would need to probably switch to using the API directly for the repo/user metadata

**Comment by tunnckoCore** [comment]
@matteofigus there is one cool api by @jonschlinkert and @doowb, `npm-api` (i think? 🤔 ) 

Or probably the `download-stats` one.

**Comment by doowb** [comment]
`npm-api` uses the same server `skimdb.npmjs.com` as the `npm-stats` library in this project. I've tried switching to `replicate.npmjs.com` as suggested in the linked issue above, however it seems that the couchdb views don't return any data. You can try to see if this project will work by setting the `url` as an option in `npm-stats`. I haven't had a chance to try it here yet.

**Comment by matteofigus** [comment]
Update: the module stats work again, while the author stats are still broken. I'm quite sure that when I checked a couple of days ago they were both broken..

**Comment by matteofigus** [comment]
Also, just deployed with the new url, and no luck. Module stats keep working, but user stats and latest updated (home page) still broken. Sounds to me that as @doowb stated in their ticket, some views are missing as returning zero results

**Comment by doowb** [comment]
@matteofigus I updated [npm-api](https://github.com/doowb/npm-api/) to use the new repo and the search api to get the list of projects/repos for a maintainer. Since most of the library relied on the couchdb views, there is still some work to be done, but this will get you to a place where `npm-stats-www` is working again.

If you just want to use the specific endpoint, you can see the [code I updated here](https://github.com/doowb/npm-api/blob/master/lib/models/maintainer.js#L43-L61).

**Comment by matteofigus** [comment]
Cool, I updated the maintainer page using npm-api and that fixed the page. I think the home is still using an old view and that still doesn't work, but for the time being most of it is ok so I'm closing. Thanks for your help!

**Comment by Mouvedia** [comment]
@matteofigus Are you sure it's fixed? Did you check users owning organisations ?

**Comment by matteofigus** [comment]
This one worked http://npm-stats.com/matteofigus - can you find a broken url? In case, I can try to troubleshoot

**Comment by Mouvedia** [comment]
@matteofigus http://www.npm-stats.com/ggozlan

**Comment by tunnckoCore** [comment]
Mine isn't loading too http://npm-stats.com/tunnckocore. It sits at 0/451 for hours.

**Comment by Mouvedia** [comment]
Maybe #11 is the culprit.

**Comment by matteofigus** [comment]
Ok, so there was a frontend issue and I fixed it, so now the page loads and downloads the individual stats. http://www.npm-stats.com/ggozlan

Unfortunately the scoped packages are broken, probably deriving from #11 so that's the thing I'm gonna try tackling next.

**Comment by matteofigus** [comment]
That's now fixed too @Mouvedia - it was just a little express issue.

**Comment by tunnckoCore** [comment]
@matteofigus great! : )
