### ISSUE TITLE
Loading downloads for …

### ISSUE THREAD

**Issue by Mouvedia** [matteofigus/npm-stats-www#6]
Nothing appearing.
It used to.

**Comment by matteofigus** [comment]
Which link?

**Comment by matteofigus** [comment]
Looks like there are some problems connecting to the data source.

**Comment by matteofigus** [comment]
This seems related: http://status.npmjs.org/incidents/4ck8z4w2p0nf

**Comment by Mouvedia** [comment]
Maybe you should fallback to something in that case.

**Comment by matteofigus** [comment]
It looks ok to me now. Maybe I should show better errors when there are errors due to  api unavailability: I'll keep this issue open for that ;)

**Comment by GitScrum** [comment]
Again Loading status for ...

**Comment by matteofigus** [comment]
@GitScrum I can't reproduce with my account: http://www.npm-stats.com/matteofigus

What's the url you are visiting?

**Comment by GitScrum** [comment]
@matteofigus now is all right, sorry
