### ISSUE TITLE
line chart disappearance

### ISSUE THREAD

**Issue by Mouvedia** [matteofigus/npm-stats-www#7]
1. visit `http://www.npm-stats.com/~packages/<example>`
2. move your mouse over one of the markers
3. click on the open on npm link
4. switch to the npm tab/window
5. switch back to the original tab/window

The line graph has disappeared!

**Comment by matteofigus** [comment]
1) Browser type?
2) Browser version?
3) OS?
4) Screenshot if possible?

Thanks

**Comment by Mouvedia** [comment]
1) ?
2) Chrome Canary
3) Mac OS X 10.10.4

I can't reproduce it. Iv updated my browser since then.

**Comment by matteofigus** [comment]
I can't as well, so I am closing this. In case, we can reopen. Thanks.
