### ISSUE TITLE
Group numbers in thousands.

### ISSUE THREAD

**Issue by lipis** [matteofigus/npm-stats-www#8]
http://www.npm-stats.com/sindresorhus
<img width="657" alt="screen shot 2015-12-14 at 18 32 08" src="https://cloud.githubusercontent.com/assets/125676/11788391/15fdd722-a291-11e5-8c27-459231b7e795.png">

**Comment by matteofigus** [comment]
:+1: are you able to make a pull request?

**Comment by lipis** [comment]
yes I'm able to.. but maybe you should do it :dancer:
