### ISSUE TITLE
new site, fork me on GitHib link

### ISSUE THREAD

**Issue by fibo** [matteofigus/npm-stats-www#9]
Hi, thank you for npm stats. I noticed today that it changed look &feel, it is really nicer than yesterday. But I see here that the last commit is 7months ago and that there is no other branch. Is this the right repo? I followed the "fork me on GitHub" badge.

**Comment by matteofigus** [comment]
Hi Gianluca, we didn't changed anything in the last couple of months. www.npm-stats.com - is this the website you clicked from?

**Comment by fibo** [comment]
Hi Matteo,

I am sorry I did a mistake, I was confused by http://npm-stat.com/
